In [3]:
# !pip install numpy

In [1]:
import numpy as np

# Creating array

In [11]:
my_list=[1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [12]:
np.array(my_list) #untuk membuat array dari data tipe lain

array([1, 2, 3, 4, 5])

In [13]:
my_list2=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_list2) #array di dalam array/ array 2 dimensi/ matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
my_list3= [
    [[1,2,3],[4,5,6],[7,8,9]],
    [[1,2,3],[4,5,6],[7,8,9]],
    [[1,2,3],[4,5,6],[7,8,9]]
]
np.array(my_list3) #array 3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

## creating array with numpy method

In [16]:
np.arange(10) #mirip dengan range di list. 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,12,2) # (start,stop, step )

array([ 0,  2,  4,  6,  8, 10])

In [18]:
np.ones(3) #array berisi hanya angka 1, biasa dipakai untuk data dummy

array([1., 1., 1.])

In [20]:
np.ones((3,3,3)) #required parameter adalah shape/bentuk dan ukuran dari array yang diinginkan

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [21]:
np.zeros(3) #mirip np.ones, tapi isinya angka 0 semua

array([0., 0., 0.])

In [23]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.eye(5) #membuat matrix berisi angka 1 di posisi diagonal, dan angka 0 di sisa datanya. digunakan untuk perhitungan algebra pada numpy

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.linspace(0,10,5) # start, stop, NUMBER/ berapa jumlah angka yang diinginkan
# membuat angka dengan jumlah tertentu dan jarak yang sama

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [28]:
np.linspace(0,10) #secara default, jumlah angka yang dihasilkan adalah 50

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [31]:
np.random.rand(4,5) # membuat array berukuran tertentu berisi angka acak dengan nilai dari 0-1

array([[0.38258586, 0.60356803, 0.60297594, 0.36495281, 0.8565985 ],
       [0.96815521, 0.03723953, 0.1858164 , 0.11042374, 0.48443093],
       [0.27180529, 0.35217787, 0.96257157, 0.45636358, 0.23436158],
       [0.30707541, 0.97198117, 0.63072192, 0.67531303, 0.87886418]])

In [38]:
np.random.randn(4,5) # membuat array berukuran tertentu berisi angka acak memiliki distribusi normal
# angka yang dihasilnya randn ada yang positif dan negatif

array([[-1.30386703, -0.77609275, -0.25199614, -1.68883076, -0.31649335],
       [-1.38022189,  1.56640338,  0.06485023, -0.75864443, -1.17127945],
       [ 0.22741441,  1.97179396, -1.00188882, -0.98662067,  0.63410182],
       [ 1.15458098,  1.65312374, -0.88080546, -0.74480906, -1.64128142]])

In [42]:
np.random.randint(10) # membuat array berisi angka integer acak dari range yang kita tentukan

4

In [45]:
np.random.randint(10,20,100) # membuat array berisi 100 angka acak di antara angka 10-20

array([10, 14, 17, 14, 19, 19, 11, 11, 18, 14, 15, 19, 12, 12, 15, 12, 19,
       14, 18, 10, 11, 13, 19, 18, 16, 10, 12, 12, 15, 12, 15, 19, 13, 19,
       19, 14, 17, 16, 17, 17, 18, 15, 19, 11, 11, 11, 17, 16, 12, 15, 18,
       13, 11, 18, 19, 12, 18, 14, 13, 14, 12, 10, 14, 15, 16, 10, 13, 10,
       14, 14, 14, 19, 19, 14, 18, 10, 12, 14, 12, 10, 19, 19, 18, 19, 13,
       14, 10, 18, 18, 10, 18, 17, 15, 10, 16, 10, 15, 16, 18, 13])

In [47]:
np.random.randint(10,20,(10,10)) #bentuk array yang dibuat adalah 10,10

array([[12, 12, 15, 10, 14, 14, 17, 15, 17, 12],
       [15, 10, 15, 19, 12, 19, 15, 11, 19, 19],
       [13, 14, 14, 12, 10, 10, 15, 17, 18, 12],
       [10, 12, 10, 17, 13, 18, 15, 16, 17, 10],
       [11, 11, 13, 13, 17, 14, 11, 13, 12, 13],
       [19, 11, 15, 12, 18, 14, 17, 15, 16, 14],
       [17, 11, 19, 17, 15, 15, 10, 18, 10, 19],
       [14, 17, 18, 12, 15, 11, 14, 12, 14, 18],
       [19, 17, 19, 10, 19, 16, 12, 19, 12, 15],
       [14, 10, 18, 18, 11, 10, 17, 14, 16, 19]])

# attribut dan methods

In [48]:
array_1d= np.arange(1,4)
array_2d=np.arange(1,10).reshape(3,-1)
array_3d=np.arange(1,28).reshape(3,3,-1)

In [49]:
array_1d

array([1, 2, 3])

In [50]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [52]:
array_1d.shape #shape adalah attribute dari array
#menampilkan ukuran dan bentuk array
# array_1d memiliki ukuran 3, dan dimensi 1

(3,)

In [53]:
array_2d.shape # ukuran dari array_2d adalah 3x3, dimensi 2

(3, 3)

In [55]:
array_3d.shape # ukuran 3x3x3, dimensi 3

(3, 3, 3)

In [57]:
array_3d.shape=-1 #asign nilai atribut yang diinginkan
array_3d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [58]:
array_3d.reshape(-1) #-1, bentuk array akan menyesuaikan nilai ukuran dimensi, berdasarkan nilai lain yang kita masukkan 
# di catatan ini kita ingin mengubah array 3d menjadi 1 dimensi

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [67]:
array_3d=np.arange(1,21).reshape(2,5,-1)
array_3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [61]:
array_3d.shape

(2, 5, 2)

In [72]:
array_3d.reshape(4,-1) #reshape untuk mengubah bentuk array. 
# di contoh ini kita ingin mengubah bentuk dan ukuran array 3d menjadi 2d.
# di mana salah satu dimensi berukuran 4, ukuran dimensi lain akan menyesuaikan sesuai jumlah data yang ada (-1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [70]:
array_1d 

array([1, 2, 3])

In [71]:
array_1d.reshape(4,-1) # error karena jumlah data tidak sesuai, array 1d memiliki 3 data

ValueError: cannot reshape array of size 3 into shape (4,newaxis)

In [74]:
my_array= np.random.randint(1,20,10)
my_array

array([14, 13, 10, 11,  1, 14, 18, 19,  8,  2])

In [75]:
np.max(my_array) #mencari nilai maximum dari suatu array

19

In [77]:
np.argmax(my_array) #mencari POSISI nilai maximum dari suatu array

7

In [78]:
my_matrix=np.random.randint(1,20,(2,5))
my_matrix

array([[18, 14, 18,  3,  9],
       [14, 14, 13, 10, 19]])

In [79]:
np.min(my_matrix) #tanpa parameter tambahan, angka yang keluar angka paling kecil

3

In [80]:
np.min(my_matrix,axis=0) # nilai terkecil di tiap kolom

array([14, 14, 13,  3,  9])

In [81]:
np.argmin(my_matrix, axis=1) # posisi nilai terkecil di tiap baris

array([3, 3], dtype=int64)

In [82]:
my_matrix.argmin(axis=1)

array([3, 3], dtype=int64)

In [83]:
my_matrix.dtype #mengecek data tipe di array

dtype('int32')

In [85]:
np.array(['a',1,2.0]) #array hanya bisa menampung 1 tipe data

array(['a', '1', '2.0'], dtype='<U3')

In [86]:
np.linspace(1,10).dtype

dtype('float64')

# Indexing and Selection

In [2]:
arr= np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
# index di array dimulai dari 0
arr[8] # menampilkan nilai di posisi index 8

8

In [90]:
arr[2:7] #slicing, menampilkan nilai di posisi 2 sampai sebelum 7

array([2, 3, 4, 5, 6])

In [91]:
arr[0:8:2] #start stop step, menampilkan nilai di index 0 sampai sebelum 8, dengan step 2/dilongkap 1

array([0, 2, 4, 6])

In [92]:
arr[::-1] #slicing dari awal sampai selesai, step mundur

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [93]:
arr[0]=10 #assign nilai 10 pada posisi index 0 di array arr
arr

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
arr[2:5]=100 #kita bisa melakukan broadcasting
# nilai 100 akan diassign pada index 2-4
arr

array([ 10,   1, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [95]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
slice_array=arr[0:5]
slice_array

array([0, 1, 2, 3, 4])

In [99]:
slice_array[:]=99
slice_array

array([99, 99, 99, 99, 99])

In [100]:
arr # isi arr ikut berubah sewaktu kita mengubah nilai slice of array. karena slice of array hanya merupakan view dari arr
# bukan array baru

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [101]:
arr2=arr.copy()
arr2[0]=1000
arr2

array([1000,   99,   99,   99,   99,    5,    6,    7,    8,    9,   10])

In [102]:
arr #pakai copy, untuk memastikan nilai arr tidak berubah sewaktu kita mengubah nilai arr2

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

## 2d

In [15]:
arr_2d=np.arange(5,46,5).reshape(3,3)
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [105]:
arr_2d[1] # mengambil data di posisi index baris 1

array([20, 25, 30])

In [108]:
arr_2d[1,0] #menampilkan data di posisi index baris 1, kolom 0

20

In [110]:
arr_2d[1][0]

20

In [111]:
arr_2d[2,0]

35

In [112]:
arr_2d[:2] #menampilkan data dimulai dari baris 0 sampai sebelum baris 2 (baris 0 dan 1)

array([[ 5, 10, 15],
       [20, 25, 30]])

In [114]:
arr_2d[:2,1:] # menampilkan data dimulai dari baris 0- sebelum 2
# dan kolom dimulai dari kolom 1 sampai selesai

array([[10, 15],
       [25, 30]])

In [116]:
arr_2d[:2][1:] # hasil berbeda karena slicing dilakukan pada hasil slicing arr2d[:2], jadi [1:] akan memotong baris

array([[20, 25, 30]])

## fancy indexing

In [117]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [118]:
list1=[0,1,2,3,4,5,6,7,8,9,10]
list1[[1,2,5,10]] #error, di list indexing dadn slicing hanya bisa dilakukan untuk data berurutan

TypeError: list indices must be integers or slices, not list

In [119]:
arr[[1,2,5,10]] #fancy indexing, indexing beberapa data secara tidak berurutan
#perhatikan jumlah kurung siku

array([ 1,  2,  5, 10])

In [3]:
arr[[9,4,6]] # bisa dilakukan secara acak

array([9, 4, 6])

In [122]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [123]:
arr_2d[[0,2]] #bisa dilakukan pada array 2d

array([[ 5, 10, 15],
       [35, 40, 45]])

## Conditional Selection
menampilkan data yang memenuhi kondisi tertentu

In [4]:
arr= np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr%3==0 #apakah nilai dalam arr bisa dibagi 3 atau tidak

array([False, False,  True, False, False,  True, False, False,  True,
       False])

In [6]:
arr[arr%3==0] #jika kondisi yang kita inginkan dimasukkan sebagai indeks, maka hanya nilai yang memenuhi syarat yang akan muncul

array([3, 6, 9])

In [7]:
arr[arr<4]

array([1, 2, 3])

## Numpy Operation

broadcasting

In [9]:
list1=[0,1,2,3,4,5]
list1

[0, 1, 2, 3, 4, 5]

In [11]:
list1*2 #nilai di dalam list diulang

[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]

In [12]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr*2 #nilai di dalam arr dikali 2. Fitur broadcasting

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

([1,2,3,4,5,6,7,8,9,10]) x ([2,2,2,2,2,2,2,2,2,2]) --> yang terjadi ketika broadcasting, angka 2 di 'stretch' sehingga memiliki ukuran sama dengan arr

In [16]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
arr1=np.arange(1,4)
arr1

array([1, 2, 3])

In [18]:
arr_2d+arr1

array([[ 6, 12, 18],
       [21, 27, 33],
       [36, 42, 48]])

In [19]:
arr_2d.shape

(3, 3)

In [20]:
arr1.shape

(3,)

In [22]:
arr_2d=np.arange(0,24).reshape(4,6)
arr_2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [33]:
arr1=np.arange(1,5)
arr1

array([1, 2, 3, 4])

In [28]:
arr_2d+arr1 #ukuran tidak sesuai

ValueError: operands could not be broadcast together with shapes (4,6) (4,) 

In [27]:
arr_2d+arr1.reshape(4,-1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 8,  9, 10, 11, 12, 13],
       [15, 16, 17, 18, 19, 20],
       [22, 23, 24, 25, 26, 27]])

In [29]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [31]:
arr*arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [32]:
arr_2d**2

array([[  0,   1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256, 289],
       [324, 361, 400, 441, 484, 529]], dtype=int32)

Mathematical Function

In [34]:
np.sqrt(arr) #mencari akar

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [35]:
np.exp(arr) #mencari exponen (x^e)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [36]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [37]:
np.log(arr) #kebalikan dari exp

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [38]:
np.log10(100)

2.0

In [39]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [43]:
arr_2d.sum() #jumlah dari semua nilai di arr

276

In [44]:
arr_2d.sum(axis=1) #jumlah per baris

array([ 15,  51,  87, 123])

In [45]:
arr_2d.sum(axis=0) #jumlah per kolom

array([36, 40, 44, 48, 52, 56])

other function

In [46]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
np.insert(arr,5,100) #memasukkan angka 100 di posisi index 5 pada array arr

array([  1,   2,   3,   4,   5, 100,   6,   7,   8,   9,  10])

In [49]:
np.delete(arr,7) #menghapus data pada posisi index 7

array([ 1,  2,  3,  4,  5,  6,  7,  9, 10])

In [67]:
np.append(arr,100) #menambahkan angka 100 pada posisi terakhir di array arr

In [68]:
arr #kalau hasil fungsi di atas tidak disimpan di arr, nilai arr tidak berubah

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 100])

In [55]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
print(a)
b

[[1 2]
 [3 4]]


array([[5, 6]])

In [69]:
b.shape

(1, 2)

In [56]:
np.concatenate((a,b)) # menggabungkan 2 array yang memiliki dimensi sama, secara default akan menggabungkan pada axis 0/baris

array([[1, 2],
       [3, 4],
       [5, 6]])

In [57]:
b.T #transpose

array([[5],
       [6]])

In [58]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [59]:
np.concatenate((a,b),axis=None) #array yang dihasilkan flat/ 1 dimensi

array([1, 2, 3, 4, 5, 6])

In [60]:
# np where

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
np.where(arr%3==0,100,arr) # mengganti nilai di dalam array arr, jika suatu kondisi terpenuhi
# apabila nilai di dalam arr bisa dibagi 3, maka ganti dengan 100, apabila tidak, biarkan tetap arr

array([  1,   2, 100,   4,   5, 100,   7,   8, 100,  10])

In [64]:
np.where(arr%2==0,'genap','ganjil')

array(['ganjil', 'genap', 'ganjil', 'genap', 'ganjil', 'genap', 'ganjil',
       'genap', 'ganjil', 'genap'], dtype='<U6')